// Code generated by MockGen. DO NOT EDIT.
// Source: batch_summarizer.go
//
// Generated by this command:
//
//	mockgen -source=batch_summarizer.go -destination=./mocks/batch_summarizer_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "log-analytics/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBatchSummarizer is a mock of BatchSummarizer interface.
type MockBatchSummarizer struct {
	ctrl     *gomock.Controller
	recorder *MockBatchSummarizerMockRecorder
	isgomock struct{}
}

// MockBatchSummarizerMockRecorder is the mock recorder for MockBatchSummarizer.
type MockBatchSummarizerMockRecorder struct {
	mock *MockBatchSummarizer
}

// NewMockBatchSummarizer creates a new mock instance.
func NewMockBatchSummarizer(ctrl *gomock.Controller) *MockBatchSummarizer {
	mock := &MockBatchSummarizer{ctrl: ctrl}
	mock.recorder = &MockBatchSummarizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchSummarizer) EXPECT() *MockBatchSummarizerMockRecorder {
	return m.recorder
}

// Summarize mocks base method.
func (m *MockBatchSummarizer) Summarize(batch *models.LogBatch) *models.BatchSummary {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summarize", batch)
	ret0, _ := ret[0].(*models.BatchSummary)
	return ret0
}

// Summarize indicates an expected call of Summarize.
func (mr *MockBatchSummarizerMockRecorder) Summarize(batch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summarize", reflect.TypeOf((*MockBatchSummarizer)(nil).Summarize), batch)
}
