// Code generated by MockGen. DO NOT EDIT.
// Source: ingestion_service.go
//
// Generated by this command:
//
//	mockgen -source=ingestion_service.go -destination=./mocks/ingestion_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	ingestors "log-analytics/internal/ingestors"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIngestionService is a mock of IngestionService interface.
type MockIngestionService struct {
	ctrl     *gomock.Controller
	recorder *MockIngestionServiceMockRecorder
	isgomock struct{}
}

// MockIngestionServiceMockRecorder is the mock recorder for MockIngestionService.
type MockIngestionServiceMockRecorder struct {
	mock *MockIngestionService
}

// NewMockIngestionService creates a new mock instance.
func NewMockIngestionService(ctrl *gomock.Controller) *MockIngestionService {
	mock := &MockIngestionService{ctrl: ctrl}
	mock.recorder = &MockIngestionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIngestionService) EXPECT() *MockIngestionServiceMockRecorder {
	return m.recorder
}

// IngestBatch mocks base method.
func (m *MockIngestionService) IngestBatch(ctx context.Context, customerID, idempotencyKey, format string, r io.Reader) (*ingestors.IngestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IngestBatch", ctx, customerID, idempotencyKey, format, r)
	ret0, _ := ret[0].(*ingestors.IngestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IngestBatch indicates an expected call of IngestBatch.
func (mr *MockIngestionServiceMockRecorder) IngestBatch(ctx, customerID, idempotencyKey, format, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestBatch", reflect.TypeOf((*MockIngestionService)(nil).IngestBatch), ctx, customerID, idempotencyKey, format, r)
}
