// Code generated by MockGen. DO NOT EDIT.
// Source: aggregation_service.go
//
// Generated by this command:
//
//	mockgen -source=aggregation_service.go -destination=./mocks/aggregation_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	events "log-analytics/internal/events"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAggregationService is a mock of AggregationService interface.
type MockAggregationService struct {
	ctrl     *gomock.Controller
	recorder *MockAggregationServiceMockRecorder
	isgomock struct{}
}

// MockAggregationServiceMockRecorder is the mock recorder for MockAggregationService.
type MockAggregationServiceMockRecorder struct {
	mock *MockAggregationService
}

// NewMockAggregationService creates a new mock instance.
func NewMockAggregationService(ctrl *gomock.Controller) *MockAggregationService {
	mock := &MockAggregationService{ctrl: ctrl}
	mock.recorder = &MockAggregationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAggregationService) EXPECT() *MockAggregationServiceMockRecorder {
	return m.recorder
}

// Aggregate mocks base method.
func (m *MockAggregationService) Aggregate(ctx context.Context, partialInsightEvent *events.PartialInsightEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Aggregate", ctx, partialInsightEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// Aggregate indicates an expected call of Aggregate.
func (mr *MockAggregationServiceMockRecorder) Aggregate(ctx, partialInsightEvent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Aggregate", reflect.TypeOf((*MockAggregationService)(nil).Aggregate), ctx, partialInsightEvent)
}
