// Code generated by MockGen. DO NOT EDIT.
// Source: aggregate_rolluper.go
//
// Generated by this command:
//
//	mockgen -source=aggregate_rolluper.go -destination=./mocks/aggregate_rolluper_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	events "log-analytics/internal/events"
	models "log-analytics/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWindowAggregateRolluper is a mock of WindowAggregateRolluper interface.
type MockWindowAggregateRolluper struct {
	ctrl     *gomock.Controller
	recorder *MockWindowAggregateRolluperMockRecorder
	isgomock struct{}
}

// MockWindowAggregateRolluperMockRecorder is the mock recorder for MockWindowAggregateRolluper.
type MockWindowAggregateRolluperMockRecorder struct {
	mock *MockWindowAggregateRolluper
}

// NewMockWindowAggregateRolluper creates a new mock instance.
func NewMockWindowAggregateRolluper(ctrl *gomock.Controller) *MockWindowAggregateRolluper {
	mock := &MockWindowAggregateRolluper{ctrl: ctrl}
	mock.recorder = &MockWindowAggregateRolluperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWindowAggregateRolluper) EXPECT() *MockWindowAggregateRolluperMockRecorder {
	return m.recorder
}

// Rollup mocks base method.
func (m *MockWindowAggregateRolluper) Rollup(agg *models.WindowAggregateResult, partial *events.PartialInsightEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollup", agg, partial)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollup indicates an expected call of Rollup.
func (mr *MockWindowAggregateRolluperMockRecorder) Rollup(agg, partial any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollup", reflect.TypeOf((*MockWindowAggregateRolluper)(nil).Rollup), agg, partial)
}
