// Code generated by MockGen. DO NOT EDIT.
// Source: partial_insight_producer.go
//
// Generated by this command:
//
//	mockgen -source=partial_insight_producer.go -destination=./mocks/partial_insight_producer_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "log-analytics/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPartialInsightProducer is a mock of PartialInsightProducer interface.
type MockPartialInsightProducer struct {
	ctrl     *gomock.Controller
	recorder *MockPartialInsightProducerMockRecorder
	isgomock struct{}
}

// MockPartialInsightProducerMockRecorder is the mock recorder for MockPartialInsightProducer.
type MockPartialInsightProducerMockRecorder struct {
	mock *MockPartialInsightProducer
}

// NewMockPartialInsightProducer creates a new mock instance.
func NewMockPartialInsightProducer(ctrl *gomock.Controller) *MockPartialInsightProducer {
	mock := &MockPartialInsightProducer{ctrl: ctrl}
	mock.recorder = &MockPartialInsightProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPartialInsightProducer) EXPECT() *MockPartialInsightProducerMockRecorder {
	return m.recorder
}

// Produce mocks base method.
func (m *MockPartialInsightProducer) Produce(ctx context.Context, batchSummary *models.BatchSummary) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Produce", ctx, batchSummary)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce.
func (mr *MockPartialInsightProducerMockRecorder) Produce(ctx, batchSummary any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockPartialInsightProducer)(nil).Produce), ctx, batchSummary)
}
