// Code generated by MockGen. DO NOT EDIT.
// Source: log_batch_store.go
//
// Generated by this command:
//
//	mockgen -source=log_batch_store.go -destination=./mocks/log_batch_store_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "log-analytics/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLogBatchStore is a mock of LogBatchStore interface.
type MockLogBatchStore struct {
	ctrl     *gomock.Controller
	recorder *MockLogBatchStoreMockRecorder
	isgomock struct{}
}

// MockLogBatchStoreMockRecorder is the mock recorder for MockLogBatchStore.
type MockLogBatchStoreMockRecorder struct {
	mock *MockLogBatchStore
}

// NewMockLogBatchStore creates a new mock instance.
func NewMockLogBatchStore(ctrl *gomock.Controller) *MockLogBatchStore {
	mock := &MockLogBatchStore{ctrl: ctrl}
	mock.recorder = &MockLogBatchStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogBatchStore) EXPECT() *MockLogBatchStoreMockRecorder {
	return m.recorder
}

// Put mocks base method.
func (m *MockLogBatchStore) Put(ctx context.Context, logBatch *models.LogBatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, logBatch)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockLogBatchStoreMockRecorder) Put(ctx, logBatch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockLogBatchStore)(nil).Put), ctx, logBatch)
}
